# .github/workflows/ci.yml

name: Run Vitest

on:
  push:
    branches: [ main, iteration2 ] # adjust to your branches
  pull_request:
    branches: [ main, iteration2 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # or whatever version you're using

      - name: Install dependencies
        run: npm install

      - name: Run Vitest
        run: npm test
