# .github/workflows/ci.yml

name: Run Vitest and Deploy

on:
  push:
    branches: [main]  # Only deploy from main branch
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Vitest
        run: npm run test

      - name: Build app
        run: npm run build
            - name: Show first 80 chars of service-account secret  # <-- TEMP debug
            
        run: |
          echo "LEN=$(echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' | wc -c)"
          echo "HEAD=$(echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' | head -c 80)"

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: studenttime-1b277
